[build]
builder = "nixpacks"

[deploy]
startCommand = "uv run python main.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
API_HOST = "0.0.0.0"
API_PORT = "8000"
DEBUG = "False"
